import {writeFileSync} from 'node:fs';
import {pages} from './src/content.js';
for(const [index,page] of pages.entries()){
 const next=pages[index+1]||pages[0],prev=pages[index-1];
 const nav=pages.map(p=>`<a href="${p.id}.html" ${page.id===p.id?'aria-current="page"':''}>${p.title}</a>`).join('');
 writeFileSync(`${page.id}.html`,`<!doctype html><html lang="kk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f5f6f2"><meta name="description" content="Қазақ тіліндегі классикалық механика зертханасы: толық математикалық қорыту, 3D тәжірибелер және нақты есептеулер."><title>${page.title} — MECHANICA</title><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='16' fill='%2315212b'/%3E%3Ctext x='12' y='46' font-size='44' fill='%23b9eed2'%3Eμ%3C/text%3E%3C/svg%3E"></head><body data-page="${page.id}" class="theme-${page.theme}"><a href="#main" class="skip">Мазмұнға өту</a><header class="site-header"><a href="index.html" class="brand"><span>μ</span> MECHANICA <small>ОҚУ АТЛАСЫ</small></a><button id="menu-toggle" aria-expanded="false" aria-controls="navigation">Мәзір ☰</button><nav id="navigation" aria-label="Негізгі мәзір">${nav}</nav></header><main id="main" class="container">${page.html}<nav class="page-turn" aria-label="Бөлімдер арасында өту">${prev?`<a href="${prev.id}.html"><small>АЛДЫҢҒЫ БӨЛІМ</small>← ${prev.title}</a>`:'<span></span>'}<a href="${next.id}.html"><small>${index===pages.length-1?'БАСЫНА ОРАЛУ':'КЕЛЕСІ БӨЛІМ'}</small>${next.title} →</a></nav></main><footer class="container"><a class="brand" href="index.html"><span>μ</span> MECHANICA</a><p>БӨЖ · Классикалық механика<br>Түсіну. Есептеу. Тексеру.</p><a href="conclusion.html">Дереккөздер және қорытынды ↗</a></footer><noscript><p class="noscript">Теория мен формулалар қолжетімді. Интерактивті тәжірибелер үшін JavaScript қосыңыз.</p></noscript><script type="module" src="/src/main.js"></script></body></html>`);
}
console.log('Generated 7 pages with validated mathematical formulas.');

