import './style.css';
import katex from 'katex';
import {motion,inverse,compare,predict} from './physics.js';
const $=id=>document.getElementById(id),page=document.body.dataset.page;
const n=id=>Number($(id).value),f=(v,d=2)=>(Math.abs(v)<1e-9?0:v).toFixed(d),vectorText=a=>'('+a.map(x=>f(x)).join('; ')+')';
const tex=(el,value)=>katex.render(value,el,{displayMode:true,throwOnError:true,strict:'error'});
const math=value=>katex.renderToString(value,{displayMode:true,throwOnError:true,strict:'error'});
const vec=a=>'\\begin{pmatrix}'+a.map(x=>f(x)).join('\\\\')+'\\end{pmatrix}';
const outputs=()=>document.querySelectorAll('input[type=range]').forEach(input=>{const out=$(input.id+'-out');if(out)out.textContent=f(Number(input.value),input.step==='.01'||input.step==='0.01'||input.step==='0.05'?2:1)+' '+input.dataset.unit;});
$('menu-toggle').addEventListener('click',()=>{const open=document.querySelector('.site-header').classList.toggle('menu-open');$('menu-toggle').setAttribute('aria-expanded',String(open));});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.site-header').classList.remove('menu-open');$('menu-toggle').setAttribute('aria-expanded','false');}});
function readouts(state){for(const key of ['r','v','a','f'])$(key+'-result').textContent=vectorText(state[key]);}
function bindScene(scene){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{scene.setView(b.dataset.view);document.querySelectorAll('[data-view]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});}));document.querySelector('[data-camera-reset]')?.addEventListener('click',()=>scene.fit());document.querySelectorAll('[data-vector]').forEach(input=>input.addEventListener('change',()=>scene.setVector(input.dataset.vector,input.checked)));}
async function initScene(id,options){const {MotionScene}=await import('./scene.js');return new MotionScene($(id),options);}
if(page==='index'){
 const scene=await initScene('hero-scene',{hero:true}),params={mass:2,force:[0,-2,0],velocity:[2,3,.6]};scene.setPath(t=>motion(params,t));scene.update(motion(params,3.2),3.2);
 const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;let visible=true,last=0,t=0;new IntersectionObserver(entries=>visible=entries[0].isIntersecting).observe($('hero-scene'));
 if(!reduce)requestAnimationFrame(function animate(now){if(last&&visible&&!document.hidden){t+=Math.min((now-last)/1000,.1);const at=3+Math.sin(t*.32)*2;scene.update(motion(params,at),at);}last=now;requestAnimationFrame(animate);});
}
if(page==='direct'){
 const scene=await initScene('direct-scene');bindScene(scene);let current={mass:2,force:[0,-2,0],velocity:[2,3,.6],origin:[0,0,0]},time=n('time'),playing=false,last=0,raf=0,lastNumeric=0;
 const stop=()=>{cancelAnimationFrame(raf);playing=false;$('play').textContent='Бастау';};
 function updateNumeric(){const s=motion(current,time),a=current.force.map(x=>x/current.mass);$('direct-numeric').innerHTML=`<p>Таңдалған деректер: m = ${f(current.mass,1)} кг, t = ${f(time)} с. Вектор компоненттерінің реті: x, y, z.</p>${math('\\vec a=\\frac{\\vec F}{m}=\\frac{1}{'+f(current.mass)+'}'+vec(current.force)+'='+vec(a)+'\\;\\mathrm{m/s^2}')}${math('\\vec v=\\vec v_0+\\vec a t='+vec(current.velocity)+'+'+vec(a)+'\\cdot'+f(time)+'='+vec(s.v)+'\\;\\mathrm{m/s}')}${math('\\vec r=\\vec r_0+\\vec v_0t+\\tfrac12\\vec at^2='+vec(s.r)+'\\;\\mathrm m')}<p>Есептер толық дәлдікпен орындалады; нәтиже экранда екі ондық таңбаға дейін дөңгелектенген. Теріс компонент вектордың тиісті оське қарсы бағытын көрсетеді.</p>`;}
 function update(numeric=true){const state=motion(current,time);scene.update(state,time);readouts(state);$('time').value=time;outputs();if(numeric)updateNumeric();}
 function readParams(){const inputs=[...document.querySelectorAll('input[type=number]')];if(inputs.some(i=>i.value.trim()===''||!Number.isFinite(i.valueAsNumber)||!i.checkValidity())){$('input-error').textContent='Барлық өріске рұқсат етілген аралықтағы сан енгізіңіз. Соңғы дұрыс есеп көрсетіліп тұр.';stop();return;}$('input-error').textContent='';current={mass:n('mass'),force:['x','y','z'].map(a=>n('f'+a)),velocity:['x','y','z'].map(a=>n('v'+a)),origin:['x','y','z'].map(a=>n('r'+a))};stop();scene.setPath(t=>motion(current,t));update();}
 document.querySelectorAll('.lab-controls input').forEach(i=>i.addEventListener('input',()=>{document.querySelectorAll('[data-preset]').forEach(b=>b.classList.remove('active'));readParams();}));
 $('time').addEventListener('input',()=>{time=n('time');stop();update();});$('play').addEventListener('click',()=>{if(playing){stop();update();return;}if(time>=6)time=0;playing=true;$('play').textContent='Кідірту';last=0;raf=requestAnimationFrame(frame);});$('reset').addEventListener('click',()=>{time=0;stop();update();});
 function frame(now){if(!playing)return;if(last&&!document.hidden){time=Math.min(6,time+Math.min((now-last)/1000,.1));update(false);if(now-lastNumeric>250){updateNumeric();lastNumeric=now;}if(time===6){stop();updateNumeric();}}last=now;if(playing)raf=requestAnimationFrame(frame);}
 document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{const data={flight:[[0,-2,0],[2,3,.6]],free:[[0,0,0],[2,1,.6]],rest:[[0,2,0],[0,0,0]]}[b.dataset.preset];$('mass').value=2;['x','y','z'].forEach((a,i)=>{$('f'+a).value=data[0][i];$('v'+a).value=data[1][i];$('r'+a).value=0;});time=2;document.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('active',x===b));readParams();}));scene.setPath(t=>motion(current,t));update();
}
if(page==='inverse'){
 const scene=await initScene('inverse-scene');bindScene(scene);let mode='polynomial';
 const proofStep=(index,title,text,formula)=>`<article class="proof-step"><span class="step-number">0${index}</span><div><h3>${title}</h3><p>${text}</p>${math(formula)}</div></article>`;
 function update(path=true){const mass=n('im'),b=n('ip'),t=n('it'),s=inverse(mode,mass,b,t),circle=mode==='circle';$('ip').dataset.unit=circle?'рад/с':'м/с²';document.querySelector('label[for="ip"]>span').textContent=circle?'Бұрыштық жылдамдық ω':'Коэффициент b';$('inverse-parameter').textContent=circle?'ω тұрақты; жылдамдықтың модулі Rω. Бағыты үздіксіз өзгереді.':'u = 1 м/с; b — y(t) мүшесінің коэффициенті. Үдеу 2b-ге тең, b-ге емес.';outputs();tex($('inverse-law'),circle?'\\vec r=R\\begin{pmatrix}\\cos\\omega t\\\\\\sin\\omega t\\\\0\\end{pmatrix},\\;R=2\\;\\mathrm m':'\\vec r=\\begin{pmatrix}ut\\\\bt^2\\\\0\\end{pmatrix},\\;u=1\\;\\mathrm{m/s}');
 if(path)scene.setPath(at=>inverse(mode,mass,b,at),circle?2*Math.PI/b:6);scene.update(s,circle?t%(2*Math.PI/b):t);readouts(s);
 const steps=circle?[
 ['Қозғалыс заңын жазу','Радиус R және бұрыштық жылдамдық ω тұрақты. φ(t) = ωt — бұрылу бұрышы.','\\vec r(t)=R(\\cos\\omega t,\\sin\\omega t,0)'],
 ['Бірінші туынды: жылдамдық','Тізбекті туынды ережесін қолданамыз: cos(ωt) туындысы −ω sin(ωt), ал sin(ωt) туындысы ω cos(ωt).','\\vec v(t)=R\\omega(-\\sin\\omega t,\\cos\\omega t,0)'],
 ['Екінші туынды: үдеу','Әр туынды тағы бір ω көбейткішін береді. Үдеу радиус-векторға қарсы бағытталған.','\\vec a(t)=-R\\omega^2(\\cos\\omega t,\\sin\\omega t,0)=-\\omega^2\\vec r'],
 ['Ньютон заңы: күш','Массаға көбейтеміз. Жылдамдықтың модулі тұрақты болғанымен, бағыты өзгеретіндіктен қорытқы күш нөл емес.','\\vec F=m\\vec a=-m\\omega^2\\vec r,\\qquad |\\vec F|=mR\\omega^2']
 ]:[
 ['Қозғалыс заңын жазу','u және b уақытқа тәуелсіз. y координатасында t² бар, сондықтан оның жылдамдығы уақытпен өзгереді.','\\vec r(t)=(ut,bt^2,0)'],
 ['Бірінші туынды: жылдамдық','Компоненттерді жеке дифференциалдаймыз: d(ut)/dt = u, d(bt²)/dt = 2bt.','\\vec v(t)=\\frac{d\\vec r}{dt}=(u,2bt,0)'],
 ['Екінші туынды: үдеу','Тұрақты u-дың туындысы нөл. 2bt мүшесінің туындысы 2b-ге тең.','\\vec a(t)=\\frac{d\\vec v}{dt}=(0,2b,0)'],
 ['Ньютон заңы: күш','Үдеудің әр компонентін m массасына көбейтеміз. Бұл мысалда қорытқы күш тұрақты.','\\vec F(t)=m\\vec a=(0,2mb,0)']];
 $('inverse-proof').innerHTML=steps.map(([title,text,formula],i)=>proofStep(i+1,title,text,formula)).join('')+proofStep(5,'Сандық нәтиже',`m = ${f(mass)} кг, ${circle?'ω':'b'} = ${f(b)} ${circle?'рад/с':'м/с²'}, t = ${f(t)} с.`, '\\vec F='+vec(s.f)+'\\;\\mathrm N');}
 ['im','ip'].forEach(id=>$(id).addEventListener('input',()=>update(true)));$('it').addEventListener('input',()=>update(false));document.querySelectorAll('[data-inverse]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.inverse;document.querySelectorAll('[data-inverse]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});update();}));update();
}
if(page==='initial'){
 function update(){outputs();const x0=n('ix'),v0=n('iv'),t=n('ict'),s=compare(x0,v0,t);$('initial-a').textContent=f(s.a)+' м';$('initial-b').textContent=f(s.b)+' м';$('initial-delta').textContent=f(s.delta)+' м';$('initial-insight').textContent=x0===0&&v0===1?'Бастапқы шарттар бірдей: графиктер барлық уақытта беттеседі.':Math.abs(s.delta)<1e-8?'Осы мезетте орындары сәйкес келеді. Бірақ бастапқы күйлері әртүрлі; графиктердің бір нүктеде қиылысуы толық беттесу емес.':`Бастапқы күйлер әртүрлі. t = ${f(t,1)} с мезетінде орындар айырмасы ${f(s.delta)} м.`;
 const points=Array.from({length:121},(_,i)=>compare(x0,v0,i/20));const min=Math.floor(Math.min(-1,...points.flatMap(p=>[p.a,p.b]))/5)*5,max=Math.ceil(Math.max(1,...points.flatMap(p=>[p.a,p.b]))/5)*5;const px=t=>60+t/6*600,py=x=>310-(x-min)/(max-min)*270;let svg='';for(let i=0;i<=5;i++){const y=min+(max-min)*i/5;svg+=`<line x1="60" y1="${py(y)}" x2="660" y2="${py(y)}" stroke="#e0e6df"/><text x="45" y="${py(y)+5}" text-anchor="end" fill="#617178" font-size="12">${f(y,0)}</text>`;}for(let i=0;i<=6;i++)svg+=`<text x="${px(i)}" y="334" text-anchor="middle" fill="#617178" font-size="12">${i}</text>`;for(const key of ['a','b'])svg+=`<path d="${points.map((p,i)=>(i?'L':'M')+px(i/20)+','+py(p[key])).join(' ')}" fill="none" stroke="${key==='a'?'#3976ad':'#c77a28'}" stroke-width="3" ${key==='b'?'stroke-dasharray="8 5"':''}/>`;svg+=`<line x1="${px(t)}" y1="40" x2="${px(t)}" y2="310" stroke="#85938e" stroke-dasharray="4 5"/><circle cx="${px(t)}" cy="${py(s.a)}" r="5" fill="#3976ad"/><circle cx="${px(t)}" cy="${py(s.b)}" r="5" fill="#c77a28"/><text x="17" y="22" fill="#617178" font-size="13">x, м</text><text x="658" y="354" fill="#617178" font-size="13">t, с</text>`;$('initial-chart').innerHTML=svg;}
 ['ix','iv','ict'].forEach(id=>$(id).addEventListener('input',update));$('same-initial').addEventListener('click',()=>{$('ix').value=0;$('iv').value=1;update();});update();
}
if(page==='causality'){function update(){outputs();const s=predict(n('ct'));$('prediction-a').textContent=f(s.analytic)+' м';$('prediction-b').textContent=f(s.stepped)+' м';$('prediction-error').textContent='200 қадам. Айырма: '+Math.abs(s.analytic-s.stepped).toExponential(1)+' м (компьютерлік дөңгелектеу).';}$('ct').addEventListener('input',update);update();}
if(page==='conclusion'){
 const questions=[['Қорытқы күш нөлге тең болса, дене міндетті түрде тоқтай ма?',['Иә, жылдамдық міндетті түрде нөл','Жоқ, жылдамдық тұрақты болып қалады','Үдеу шексіз өседі'],1,'F = 0 болса, a = 0. Дененің жылдамдығы нөл болуы да, тұрақты нөлден өзгеше болуы да мүмкін.'],['Екінші ретті қозғалыс теңдеуінің нақты шешімі үшін не қажет?',['Тек бастапқы орын','Тек масса','Бастапқы орын мен бастапқы жылдамдық'],2,'Күш заңы мен масса берілгенде r₀ және v₀ интегралдаудың екі векторлық тұрақтысын анықтайды.'],['y(t) = bt² болса, y осіндегі үдеу нешеге тең?',['b','2b','2bt'],1,'Бірінші туынды: v_y = 2bt. Екінші туынды: a_y = 2b.'],['Шеңбер бойымен бірқалыпты қозғалыста қорытқы күштің бағыты қандай?',['Жанама бойымен','Орталыққа қарай','Орталықтан сыртқа'],1,'F = −mω²r: минус таңбасы радиус-векторға қарсы, орталыққа бағытталуды білдіреді.'],['Детерминизм нені білдіреді?',['Кез келген уақытқа шексіз дәл практикалық болжам','Дәл бастапқы күй үшін модель шешімінің бірмәнділігі','Барлық қозғалыс түзу сызықты'],1,'Детерминизм мен практикалық болжамдылық бөлек ұғымдар. Өлшеу дәлдігі және бастапқы шарттарға сезімталдық маңызды.']];let index=0,answered=false;
 function draw(){answered=false;const q=questions[index];$('quiz-question').textContent=q[0];$('quiz-options').innerHTML=q[1].map((text,i)=>`<button data-answer="${i}">${text}</button>`).join('');$('quiz-feedback').textContent='';$('quiz-progress').textContent=`${index+1} / ${questions.length}`;document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{if(answered)return;answered=true;const correct=Number(b.dataset.answer)===q[2];b.classList.add(correct?'correct':'incorrect');document.querySelector(`[data-answer="${q[2]}"]`).classList.add('correct');$('quiz-feedback').textContent=(correct?'Дұрыс. ':'Қайта ойланайық. ')+q[3];}));}$('quiz-next').addEventListener('click',()=>{index=(index+1)%questions.length;draw();});draw();
}
outputs();

