import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const colors={r:0x91bfff,v:0x9ef1c5,a:0xffcf76,f:0xfa97bf};
const factors={r:1,v:.6,a:1,f:.75};
const vector=a=>new THREE.Vector3(...a);
function disposeObject(object){object.traverse(o=>{o.geometry?.dispose();if(o.material){const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>{m.map?.dispose();m.dispose();});}});}
function label(value,color='#b9d0d6'){const c=document.createElement('canvas');c.width=128;c.height=64;const ctx=c.getContext('2d');ctx.font='bold 42px Arial';ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(value,64,41);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false}));return sprite;}
export class MotionScene{
 constructor(container,{hero=false}={}){
  this.el=container;this.hero=hero;this.state=null;this.view='3d';this.extent=10;this.duration=6;this.show={r:true,v:true,a:true,f:true};
  this.world=new THREE.Scene();this.world.background=new THREE.Color(hero?0x10232a:0x11242d);this.world.fog=new THREE.Fog(this.world.background,70,200);
  try{this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});}catch{this.fallback=true;this.el.innerHTML='<div class="scene-fallback"><strong>WebGL қолжетімсіз.</strong><p>Траектория төменде XY проекциясында көрсетіледі. Сандық есеп пен формулалар жұмыс істейді.</p><svg viewBox="0 0 500 260" aria-label="XY проекциясындағы траектория"></svg></div>';return;}
  this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.setClearColor(this.world.background);container.append(this.renderer.domElement);
  this.camera=new THREE.PerspectiveCamera(38,1,.01,2000);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=false;this.controls.enablePan=!hero;this.controls.enableZoom=!hero;this.controls.enabled=!hero;this.controls.addEventListener('change',()=>this.render());
  this.world.add(new THREE.AmbientLight(0xcde3ee,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(8,12,10);this.world.add(light);
  this.body=new THREE.Mesh(new THREE.SphereGeometry(1,24,16),new THREE.MeshStandardMaterial({color:0xb9eed2,emissive:0x224b3e,metalness:.25,roughness:.28}));this.world.add(this.body);
  this.arrows={};this.labels={};for(const key of Object.keys(colors)){this.arrows[key]=new THREE.ArrowHelper(new THREE.Vector3(1,0,0),new THREE.Vector3(),1,colors[key]);this.world.add(this.arrows[key]);this.labels[key]=label(key==='f'?'F':key,'#'+colors[key].toString(16));this.world.add(this.labels[key]);}
  this.staticGroup=new THREE.Group();this.world.add(this.staticGroup);
  this.status=document.createElement('span');this.status.className='scene-status';container.append(this.status);
  this.renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();this.status.textContent='3D көрінісі уақытша тоқтады. Бетті жаңартыңыз; есептеулер сақталады.';});
  this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);
  container.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key)||hero)return;e.preventDefault();const offset=this.camera.position.clone().sub(this.controls.target),spherical=new THREE.Spherical().setFromVector3(offset);if(e.key==='ArrowLeft')spherical.theta-=.12;if(e.key==='ArrowRight')spherical.theta+=.12;if(e.key==='ArrowUp')spherical.phi-=.12;if(e.key==='ArrowDown')spherical.phi+=.12;if(e.key==='+')spherical.radius*=.9;if(e.key==='-')spherical.radius*=1.1;spherical.phi=THREE.MathUtils.clamp(spherical.phi,.05,Math.PI-.05);this.camera.position.copy(this.controls.target).add(new THREE.Vector3().setFromSpherical(spherical));this.controls.update();this.render();});
 }
 resize(){if(this.fallback)return;const w=this.el.clientWidth,h=this.el.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();if(this.box)this.fit();this.render();}
 setPath(sample,duration=6){this.sample=sample;this.duration=duration;this.samples=Array.from({length:181},(_,i)=>sample(i/180*duration));if(this.fallback){this.drawFallback();return;}
  this.world.remove(this.staticGroup);disposeObject(this.staticGroup);this.staticGroup=new THREE.Group();this.world.add(this.staticGroup);
  const points=this.samples.map(s=>vector(s.r)),box=new THREE.Box3().setFromPoints([...points,new THREE.Vector3()]);
  for(const s of this.samples)for(const key of ['v','a','f'])box.expandByPoint(vector(s.r).addScaledVector(vector(s[key]),factors[key]));
  this.box=box;const size=box.getSize(new THREE.Vector3());this.extent=Math.max(4,size.x,size.y,size.z);this.body.scale.setScalar(this.extent*.018);
  const trajectory=new THREE.BufferGeometry().setFromPoints(points);const dotted=new THREE.Line(trajectory,new THREE.LineDashedMaterial({color:0x51797d,dashSize:this.extent*.018,gapSize:this.extent*.012,transparent:true,opacity:.65}));dotted.computeLineDistances();this.staticGroup.add(dotted); if(points.some(p=>p.distanceTo(points[0])>1e-6)){const curve=new THREE.CatmullRomCurve3(points);const tube=new THREE.Mesh(new THREE.TubeGeometry(curve,180,this.extent*.003,6,false),new THREE.MeshBasicMaterial({color:0xa8ecd0,transparent:true,opacity:.3}));this.staticGroup.add(tube);}
  this.trace=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0xa8ecd0}));this.staticGroup.add(this.trace);
  const raw=this.extent/9,base=10**Math.floor(Math.log10(raw)),step=raw/base>5?10*base:raw/base>2?5*base:raw/base>1?2*base:base;const gridSize=step*20;const grid=new THREE.GridHelper(gridSize,20,0x507377,0x294750);grid.material.transparent=true;grid.material.opacity=.52;this.staticGroup.add(grid);this.status.textContent=`Тор қадамы: ${step} м · аналитикалық шешім`;
  for(const [i,axis] of [[0,'x'],[1,'y'],[2,'z']]){const direction=new THREE.Vector3();direction.setComponent(i,1);const length=this.extent*.72;const a=new THREE.ArrowHelper(direction,new THREE.Vector3(),length,0x698990,this.extent*.035,this.extent*.012);this.staticGroup.add(a);const l=label(axis);l.scale.set(this.extent*.16,this.extent*.08,1);l.position.copy(direction).multiplyScalar(length+this.extent*.05);this.staticGroup.add(l);}
  this.originLabel=label('O');this.originLabel.scale.set(this.extent*.07,this.extent*.035,1);this.originLabel.position.set(-this.extent*.035,-this.extent*.035,0);this.staticGroup.add(this.originLabel);
  this.fit();if(this.state)this.update(this.state,this.time||0);else this.update(this.samples[0],0);
 }
 fit(){if(this.fallback||!this.box)return;const center=this.box.getCenter(new THREE.Vector3());const sphere=this.box.getBoundingSphere(new THREE.Sphere());const radius=Math.max(2.4,sphere.radius);const fov=this.camera.fov*Math.PI/180;const vfov=this.camera.aspect<1?2*Math.atan(Math.tan(fov/2)*this.camera.aspect):fov;const distance=radius/Math.sin(vfov/2)*1.14;const dir=this.view==='xy'?new THREE.Vector3(0,0,1):this.view==='xz'?new THREE.Vector3(0,1,.0001):new THREE.Vector3(1,.65,1.35).normalize();this.camera.up.set(0,1,0);if(this.view==='xz')this.camera.up.set(0,0,-1);this.controls.target.copy(center);this.camera.position.copy(center).addScaledVector(dir,distance);this.camera.near=Math.max(.01,distance/1000);this.camera.far=distance*20;this.camera.updateProjectionMatrix();this.controls.minDistance=radius*.4;this.controls.maxDistance=distance*4;this.world.fog.near=distance*1.5;this.world.fog.far=distance*4;this.controls.update();this.render();}
 setView(view){this.view=view;this.fit();}
 update(state,time){this.state=state;this.time=time;if(this.fallback){this.drawFallback();return;}this.body.position.copy(vector(state.r));for(const key of Object.keys(this.arrows)){const start=key==='r'?new THREE.Vector3():vector(state.r),delta=vector(state[key]).multiplyScalar(factors[key]),length=delta.length();const visible=this.show[key]&&length>1e-9;this.arrows[key].visible=visible;this.labels[key].visible=visible;if(!visible)continue;this.arrows[key].position.copy(start);this.arrows[key].setDirection(delta.clone().normalize());this.arrows[key].setLength(length,Math.min(length*.25,this.extent*.035),Math.min(length*.12,this.extent*.016));this.labels[key].position.copy(start).add(delta).add(new THREE.Vector3(this.extent*.022,this.extent*.027,0));this.labels[key].scale.set(this.extent*.16,this.extent*.08,1);}
  if(this.trace)this.trace.geometry.setDrawRange(0,Math.min(181,Math.floor(time/this.duration*180)+1));this.render();
 }
 setVector(key,visible){this.show[key]=visible;if(this.state)this.update(this.state,this.time);}
 render(){if(!this.fallback)this.renderer.render(this.world,this.camera);}
 drawFallback(){if(!this.sample)return;const svg=this.el.querySelector('svg'),points=this.samples.map(s=>s.r),xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),minX=Math.min(0,...xs),maxX=Math.max(minX+1,...xs),minY=Math.min(0,...ys),maxY=Math.max(minY+1,...ys);const p=v=>[30+(v[0]-minX)/(maxX-minX)*430,230-(v[1]-minY)/(maxY-minY)*190];const d=points.map((v,i)=>(i?'L':'M')+p(v).join(',')).join(' '),q=p(this.state?.r||points[0]);svg.innerHTML=`<path d="${d}" fill="none" stroke="#b9eed2" stroke-width="2"/><circle cx="${q[0]}" cy="${q[1]}" r="5" fill="#b9eed2"/><text x="30" y="255" fill="#d7e9e4" font-size="12">XY проекциясы</text>`;}
}

